"""M1: users, sessions, email_tokens, rate_limits, outbox_jobs

Revision ID: 0002_m1_auth
Revises: 0001_enums
Create Date: 2026-08-27 10:31:46.541892
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0002_m1_auth"
down_revision: str | None = "0001_enums"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("outbox_jobs_pkey")),
    )
    op.create_index(
        "outbox_ready_idx",
        "outbox_jobs",
        ["run_after"],
        unique=False,
        postgresql_where=sa.text("completed_at IS NULL AND locked_at IS NULL"),
    )
    op.create_table(
        "rate_limits",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key", "window_start", name=op.f("rate_limits_pkey")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_guest", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(is_guest AND email IS NULL AND password_hash IS NULL) OR (NOT is_guest AND email IS NOT NULL AND password_hash IS NOT NULL)",
            name=op.f("users_credentials_ck"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint("email", name=op.f("users_email_uq")),
    )
    op.create_index(
        "users_guest_reap_idx",
        "users",
        ["last_seen_at"],
        unique=False,
        postgresql_where=sa.text("is_guest IS true"),
    )
    op.create_table(
        "email_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "purpose",
            postgresql.ENUM(
                "VERIFY_EMAIL", "RESET_PASSWORD", name="email_token_purpose", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("email_tokens_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("email_tokens_pkey")),
    )
    op.create_index("email_tokens_hash_uq", "email_tokens", ["token_hash"], unique=True)
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("csrf_secret", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent_hash", sa.LargeBinary(), nullable=True),
        sa.Column("ip_hash", sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("sessions_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sessions_pkey")),
    )
    op.create_index("sessions_token_uq", "sessions", ["token_hash"], unique=True)
    op.create_index(
        "sessions_user_idx",
        "sessions",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "sessions_user_idx", table_name="sessions", postgresql_where=sa.text("revoked_at IS NULL")
    )
    op.drop_index("sessions_token_uq", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("email_tokens_hash_uq", table_name="email_tokens")
    op.drop_table("email_tokens")
    op.drop_index(
        "users_guest_reap_idx", table_name="users", postgresql_where=sa.text("is_guest IS true")
    )
    op.drop_table("users")
    op.drop_table("rate_limits")
    op.drop_index(
        "outbox_ready_idx",
        table_name="outbox_jobs",
        postgresql_where=sa.text("completed_at IS NULL AND locked_at IS NULL"),
    )
    op.drop_table("outbox_jobs")
    # ### end Alembic commands ###
